
const characters = [
  { name: "곽향", tiers: ["op", "0", "op", "op", "op"] },
  { name: "개척자 (보존)", tiers: ["5", "5", "5", "5", "5"] },
  { name: "백로", tiers: ["4", "4", "4", "4", "4"] },
  { name: "부현", tiers: ["3", "3", "3", "3", "3"] },
  { name: "나찰", tiers: ["1", "2", "3", "2", "2"] },
  { name: "게파드", tiers: ["4", "4", "4", "4", "4"] },
  { name: "어벤츄린", tiers: ["1", "1", "2", "4", "4"] },
  { name: "링스", tiers: ["5", "5", "5", "5", "5"] },
  { name: "나타샤", tiers: ["5", "5", "5", "5", "5"] },
  { name: "Mar. 7th", tiers: ["5", "5", "5", "5", "5"] },
  { name: "갤러거", tiers: ["1", "1", "1", "3", "3"] },
  { name: "영사", tiers: ["0", "0", "0", "0", "0"] },
  { name: "히아킨", tiers: ["op", "op", "op", "op", "op"] },
  { name: "단항•등황", tiers: ["op", "op", "op", "op", "op"] },
  { name: "블랙 스완", tiers: ["0", "0", "0", "0", "0"] },
  { name: "스파클", tiers: ["0", "0", "0", "0", "0"] },
  { name: "완•매", tiers: ["2", "2", "2", "2", "2"] },
  { name: "브로냐", tiers: ["2", "4", "4", "2", "2"] },
  { name: "은랑", tiers: ["2", "2", "2", "2", "2"] },
  { name: "웰트", tiers: ["5", "5", "5", "5", "5"] },
  { name: "로빈", tiers: ["1", "1", "1", "1", "1"] },
  { name: "한아", tiers: ["5", "5", "5", "5", "5"] },
  { name: "계네빈", tiers: ["5", "5", "5", "5", "5"] },
  { name: "어공", tiers: ["5", "5", "5", "5", "5"] },
  { name: "정운", tiers: ["1", "3", "3", "1", "1"] },
  { name: "페라", tiers: ["3", "3", "3", "3", "3"] },
  { name: "아스타", tiers: ["5", "5", "5", "5", "5"] },
  { name: "개척자 (화합)", tiers: ["1", "1", "1", "1", "1"] },
  { name: "초구", tiers: ["2", "2", "1", "2", "2"] },
  { name: "선데이", tiers: ["0", "0", "0", "0", "0"] },
  { name: "망귀인", tiers: ["0", "0", "0", "0", "0"] },
  { name: "트리비", tiers: ["op", "op", "op", "op", "op"] },
  { name: "개척자 (기억)", tiers: ["1", "1", "1", "1", "1"] },
  { name: "사이퍼", tiers: ["1", "1", "2", "1", "1"] },
  { name: "케리드라", tiers: ["op", "op", "op", "op", "op"] },
  { name: "키레네", tiers: ["op", "op", "op", "op", "op"] },
  { name: "달리아", tiers: ["0", "0", "0", "0", "0"] },
  { name: "경류", tiers: ["2", "2", "2", "2", "2"] },
  { name: "단항•음월", tiers: ["4", "4", "4", "4", "4"] },
  { name: "아젠티", tiers: ["4", "4", "op", "4", "4"] },
  { name: "토파즈 & 복순이", tiers: ["2", "2", "4", "2", "2"] },
  { name: "Dr. 레이시오", tiers: ["4", "4", "4", "4", "4"] },
  { name: "블레이드", tiers: ["2", "2", "2", "2", "2"] },
  { name: "경원", tiers: ["4", "4", "4", "4", "4"] },
  { name: "클라라", tiers: ["5", "5", "5", "5", "5"] },
  { name: "제레", tiers: ["3", "4", "4", "4", "4"] },
  { name: "카프카", tiers: ["0", "0", "0", "0", "0"] },
  { name: "히메코", tiers: ["5", "3", "0", "5", "5"] },
  { name: "연경", tiers: ["5", "5", "5", "5", "5"] },
  { name: "아케론", tiers: ["1", "1", "1", "1", "1"] },
  { name: "부트힐", tiers: ["0", "0", "3", "0", "0"] },
  { name: "개척자 (파멸)", tiers: ["5", "5", "5", "5", "5"] },
  { name: "미샤", tiers: ["5", "5", "5", "5", "5"] },
  { name: "설의", tiers: ["5", "5", "5", "5", "5"] },
  { name: "소상", tiers: ["5", "5", "5", "5", "5"] },
  { name: "청작", tiers: ["5", "4", "5", "5", "5"] },
  { name: "루카", tiers: ["5", "5", "5", "5", "5"] },
  { name: "후크", tiers: ["5", "5", "5", "5", "5"] },
  { name: "삼포", tiers: ["5", "5", "5", "5", "5"] },
  { name: "서벌", tiers: ["5", "5", "4", "5", "5"] },
  { name: "헤르타", tiers: ["5", "5", "op", "5", "5"] },
  { name: "아를란", tiers: ["5", "5", "5", "5", "5"] },
  { name: "단항", tiers: ["5", "5", "5", "5", "5"] },
  { name: "제이드", tiers: ["3", "1", "op", "5", "5"] },
  { name: "반디", tiers: ["op", "op", "op", "op", "op"] },
  { name: "Mar. 7th (수렵)", tiers: ["4", "4", "4", "4", "4"] },
  { name: "운리", tiers: ["2", "2", "2", "2", "2"] },
  { name: "맥택", tiers: ["4", "4", "4", "4", "4"] },
  { name: "비소", tiers: ["1", "1", "1", "1", "1"] },
  { name: "라파", tiers: ["1", "1", "1", "1", "1"] },
  { name: "더 헤르타", tiers: ["1", "1", "1", "1", "1"] },
  { name: "아글라이아", tiers: ["0", "0", "0", "0", "0"] },
  { name: "마이데이", tiers: ["1", "1", "1", "1", "1"] },
  { name: "카스토리스", tiers: ["op", "op", "op", "op", "op"] },
  { name: "아낙사", tiers: ["op", "op", "op", "op", "op"] },
  { name: "파이논", tiers: ["op", "op", "op", "op", "op"] },
  { name: "아처", tiers: ["op", "op", "op", "op", "op"] },
  { name: "세이버", tiers: ["1", "1", "1", "1", "1"] },
  { name: "히실렌스", tiers: ["0", "0", "0", "0", "0"] },
  { name: "에버나이트", tiers: ["op", "op", "op", "op", "op"] },
];

const charInfo = {
  "곽향": { id: "char_곽향", folderName: "곽향", role: "탱커/힐러" },
  "개척자 (보존)": { id: "char_개척자_보존", folderName: "개척자 (보존)", role: "탱커/힐러", isTrailblazer: true },
  "백로": { id: "char_백로", folderName: "백로", role: "탱커/힐러" },
  "부현": { id: "char_부현", folderName: "부현", role: "탱커/힐러" },
  "나찰": { id: "char_나찰", folderName: "나찰", role: "탱커/힐러" },
  "게파드": { id: "char_게파드", folderName: "게파드", role: "탱커/힐러" },
  "어벤츄린": { id: "char_어벤츄린", folderName: "어벤츄린", role: "탱커/힐러" },
  "링스": { id: "char_링스", folderName: "링스", role: "탱커/힐러" },
  "나타샤": { id: "char_나타샤", folderName: "나타샤", role: "탱커/힐러" },
  "Mar. 7th": { id: "char_Mar_7th", folderName: "Mar. 7th", role: "탱커/힐러" },
  "갤러거": { id: "char_갤러거", folderName: "갤러거", role: "탱커/힐러" },
  "영사": { id: "char_영사", folderName: "영사", role: "탱커/힐러" },
  "히아킨": { id: "char_히아킨", folderName: "히아킨", role: "탱커/힐러" },
  "단항•등황": { id: "char_단항등황", folderName: "단항•등황", role: "탱커/힐러" },
  "블랙 스완": { id: "char_블랙_스완", folderName: "블랙 스완", role: "서포터" },
  "스파클": { id: "char_스파클", folderName: "스파클", role: "서포터" },
  "완•매": { id: "char_완매", folderName: "완•매", role: "서포터" },
  "브로냐": { id: "char_브로냐", folderName: "브로냐", role: "서포터" },
  "은랑": { id: "char_은랑", folderName: "은랑", role: "서포터" },
  "웰트": { id: "char_웰트", folderName: "웰트", role: "서포터" },
  "로빈": { id: "char_로빈", folderName: "로빈", role: "서포터" },
  "한아": { id: "char_한아", folderName: "한아", role: "서포터" },
  "계네빈": { id: "char_계네빈", folderName: "계네빈", role: "서브 딜러" },
  "어공": { id: "char_어공", folderName: "어공", role: "서포터" },
  "정운": { id: "char_정운", folderName: "정운", role: "서포터" },
  "페라": { id: "char_페라", folderName: "페라", role: "서포터" },
  "아스타": { id: "char_아스타", folderName: "아스타", role: "서포터" },
  "개척자 (화합)": { id: "char_개척자_화합", folderName: "개척자 (화합)", role: "서포터", isTrailblazer: true },
  "초구": { id: "char_초구", folderName: "초구", role: "서포터" },
  "선데이": { id: "char_선데이", folderName: "선데이", role: "서포터" },
  "망귀인": { id: "char_망귀인", folderName: "망귀인", role: "서포터" },
  "트리비": { id: "char_트리비", folderName: "트리비", role: "서포터" },
  "개척자 (기억)": { id: "char_개척자_기억", folderName: "개척자 (기억)", role: "서포터", isTrailblazer: true },
  "사이퍼": { id: "char_사이퍼", folderName: "사이퍼", role: "서브 딜러" },
  "케리드라": { id: "char_케리드라", folderName: "케리드라", role: "서포터" },
  "키레네": { id: "char_키레네", folderName: "키레네", role: "서포터" },
  "달리아": { id: "char_달리아", folderName: "달리아", role: "서포터" },
  "경류": { id: "char_경류", folderName: "경류", role: "메인 딜러" },
  "단항•음월": { id: "char_단항음월", folderName: "단항•음월", role: "메인 딜러" },
  "아젠티": { id: "char_아젠티", folderName: "아젠티", role: "메인 딜러" },
  "토파즈 & 복순이": { id: "char_토파즈_복순이", folderName: "토파즈 & 복순이", role: "서브 딜러" },
  "Dr. 레이시오": { id: "char_Dr_레이시오", folderName: "Dr. 레이시오", role: "메인 딜러" },
  "블레이드": { id: "char_블레이드", folderName: "블레이드", role: "메인 딜러" },
  "경원": { id: "char_경원", folderName: "경원", role: "메인 딜러" },
  "클라라": { id: "char_클라라", folderName: "클라라", role: "메인 딜러" },
  "제레": { id: "char_제레", folderName: "제레", role: "메인 딜러" },
  "카프카": { id: "char_카프카", folderName: "카프카", role: "메인 딜러" },
  "히메코": { id: "char_히메코", folderName: "히메코", role: "메인 딜러" },
  "연경": { id: "char_연경", folderName: "연경", role: "메인 딜러" },
  "아케론": { id: "char_아케론", folderName: "아케론", role: "메인 딜러" },
  "부트힐": { id: "char_부트힐", folderName: "부트힐", role: "메인 딜러" },
  "개척자 (파멸)": { id: "char_개척자_파멸", folderName: "개척자 (파멸)", role: "메인 딜러", isTrailblazer: true },
  "미샤": { id: "char_미샤", folderName: "미샤", role: "메인 딜러" },
  "설의": { id: "char_설의", folderName: "설의", role: "메인 딜러" },
  "소상": { id: "char_소상", folderName: "소상", role: "메인 딜러" },
  "청작": { id: "char_청작", folderName: "청작", role: "메인 딜러" },
  "루카": { id: "char_루카", folderName: "루카", role: "서브 딜러" },
  "후크": { id: "char_후크", folderName: "후크", role: "메인 딜러" },
  "삼포": { id: "char_삼포", folderName: "삼포", role: "서브 딜러" },
  "서벌": { id: "char_서벌", folderName: "서벌", role: "서브 딜러" },
  "헤르타": { id: "char_헤르타", folderName: "헤르타", role: "메인 딜러" },
  "아를란": { id: "char_아를란", folderName: "아를란", role: "메인 딜러" },
  "단항": { id: "char_단항", folderName: "단항", role: "메인 딜러" },
  "제이드": { id: "char_제이드", folderName: "제이드", role: "메인 딜러" },
  "반디": { id: "char_반디", folderName: "반디", role: "메인 딜러" },
  "Mar. 7th (수렵)": { id: "char_Mar_7th_Hunt", folderName: "Mar. 7th (수렵)", role: "서브 딜러" },
  "운리": { id: "char_운리", folderName: "운리", role: "메인 딜러" },
  "맥택": { id: "char_맥택", folderName: "맥택", role: "서브 딜러" },
  "비소": { id: "char_비소", folderName: "비소", role: "메인 딜러" },
  "라파": { id: "char_라파", folderName: "라파", role: "메인 딜러" },
  "더 헤르타": { id: "char_더_헤르타", folderName: "더 헤르타", role: "메인 딜러" },
  "아글라이아": { id: "char_아글라이아", folderName: "아글라이아", role: "메인 딜러" },
  "마이데이": { id: "char_마이데이", folderName: "마이데이", role: "메인 딜러" },
  "카스토리스": { id: "char_카스토리스", folderName: "카스토리스", role: "메인 딜러" },
  "아낙사": { id: "char_아낙사", folderName: "아낙사", role: "메인 딜러" },
  "파이논": { id: "char_파이논", folderName: "파이논", role: "메인 딜러" },
  "아처": { id: "char_아처", folderName: "아처", role: "메인 딜러" },
  "세이버": { id: "char_세이버", folderName: "세이버", role: "메인 딜러" },
  "히실렌스": { id: "char_히실렌스", folderName: "히실렌스", role: "메인 딜러" },
  "에버나이트": { id: "char_에버나이트", folderName: "에버나이트", role: "서브 딜러" },
};

const tierConfig = [
  { tier: "OP", label: "OP", color: "#FF4D4D" },
  { tier: "0", label: "0", color: "#FF9F43" },
  { tier: "1", label: "1", color: "#1DD1A1" },
  { tier: "2", label: "2", color: "#54A0FF" },
  { tier: "3", label: "3", color: "#A8A8A8" },
  { tier: "4", label: "4", color: "#5F27CD" },
  { tier: "5", label: "5", color: "#8395A7" },
];

const tierMap = {
  "op": "OP",
  "0": "0",
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  "5": "5",
};

const modes = ["chaos", "simulation", "fiction", "shadow", "divergent"];
const result = {};

modes.forEach((mode, modeIdx) => {
  result[mode] = tierConfig.map(config => ({
    ...config,
    characters: []
  }));

  characters.forEach(char => {
    const tierKey = char.tiers[modeIdx];
    const tierId = tierMap[tierKey];
    const group = result[mode].find(g => g.tier === tierId);
    if (group) {
      const info = charInfo[char.name];
      if (info) {
        group.characters.push({
          ...info,
          name: char.name,
          change: "stay"
        });
      }
    }
  });
});

console.log(JSON.stringify(result, null, 2));
