INSERT INTO tier_lists (game_id, category_id, character_name, role, tier, change) VALUES
('hsr', 'chaos', '스파키', '메인 딜러', 'OP', 'stay'),
('hsr', 'chaos', '효광', '서포터', 'OP', 'stay'),
('hsr', 'chaos', '에버나이트', '서브 딜러', 'SS', 'stay'),
('hsr', 'chaos', '애쉬베일', '서브 딜러', 'SS', 'stay'),
('hsr', 'chaos', '카스토리스', '메인 딜러', 'SS', 'stay'),
('hsr', 'chaos', '키레네', '서포터', 'SS', 'stay'),
('hsr', 'chaos', '히아킨', '유지력', 'SS', 'stay'),
('hsr', 'chaos', '히실렌스', '메인 딜러', 'SS', 'stay'),
('hsr', 'chaos', '반디', '메인 딜러', 'S+', 'stay'),
('hsr', 'chaos', '달리아', '서포터', 'S+', 'stay'),
('hsr', 'chaos', '트리비', '서포터', 'S+', 'stay'),
('hsr', 'chaos', '스파클', '서포터', 'S+', 'stay'),
('hsr', 'chaos', '아처', '메인 딜러', 'S+', 'stay'),
('hsr', 'chaos', '단항•등황', '유지력', 'S+', 'stay'),
('hsr', 'chaos', '아낙사', '메인 딜러', 'S', 'stay'),
('hsr', 'chaos', '카프카', '메인 딜러', 'S', 'stay'),
('hsr', 'chaos', '블랙 스완', '서포터', 'S', 'stay'),
('hsr', 'chaos', '케리드라', '서포터', 'S', 'stay'),
('hsr', 'chaos', '망귀인', '서포터', 'S', 'stay'),
('hsr', 'chaos', '곽향', '유지력', 'S', 'stay'),
('hsr', 'chaos', '파이논', '메인 딜러', 'A', 'stay'),
('hsr', 'chaos', '사이퍼', '서브 딜러', 'A', 'stay'),
('hsr', 'chaos', '선데이', '서포터', 'A', 'stay'),
('hsr', 'chaos', '완•매', '서포터', 'A', 'stay'),
('hsr', 'chaos', '영사', '유지력', 'A', 'stay'),
('hsr', 'chaos', '부현', '유지력', 'A', 'stay'),
('hsr', 'chaos', '마이데이', '메인 딜러', 'B', 'stay'),
('hsr', 'chaos', '아글라이아', '메인 딜러', 'B', 'stay'),
('hsr', 'chaos', '은랑', '서포터', 'B', 'stay'),
('hsr', 'chaos', '어벤츄린', '유지력', 'B', 'stay'),
('hsr', 'chaos', '갤러거', '유지력', 'B', 'stay'),
('hsr', 'chaos', '라파', '메인 딜러', 'C', 'stay'),
('hsr', 'chaos', '부트힐', '메인 딜러', 'C', 'stay'),
('hsr', 'chaos', '더 헤르타', '메인 딜러', 'C', 'stay'),
('hsr', 'chaos', '세이버', '메인 딜러', 'C', 'stay'),
('hsr', 'chaos', '로빈', '서포터', 'C', 'stay'),
('hsr', 'chaos', '나찰', '유지력', 'C', 'stay'),
('hsr', 'chaos', '비소', '메인 딜러', 'D', 'stay'),
('hsr', 'chaos', '아케론', '메인 딜러', 'D', 'stay'),
('hsr', 'chaos', '제이드', '메인 딜러', 'D', 'stay'),
('hsr', 'chaos', '블레이드', '메인 딜러', 'D', 'stay'),
('hsr', 'chaos', '초구', '서포터', 'D', 'stay'),
('hsr', 'chaos', '페라', '서포터', 'D', 'stay'),
('hsr', 'chaos', '맥택', '서브 딜러', 'D', 'stay'),
('hsr', 'chaos', '경류', '메인 딜러', 'E', 'stay'),
('hsr', 'chaos', '운리', '메인 딜러', 'E', 'stay'),
('hsr', 'chaos', '경원', '메인 딜러', 'E', 'stay'),
('hsr', 'chaos', '브로냐', '서포터', 'E', 'stay'),
('hsr', 'chaos', '정운', '서포터', 'E', 'stay'),
('hsr', 'chaos', 'Mar. 7th (수렵)', '서브 딜러', 'E', 'stay'),
('hsr', 'chaos', '히메코', '메인 딜러', 'E', 'stay'),
('hsr', 'chaos', '토파즈 & 복순이', '서브 딜러', 'E', 'stay'),
('hsr', 'chaos', 'Dr. 레이시오', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '단항•음월', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '아젠티', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '미샤', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '설의', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '한아', '서포터', 'F', 'stay'),
('hsr', 'chaos', '계네빈', '서브 딜러', 'F', 'stay'),
('hsr', 'chaos', '링스', '유지력', 'F', 'stay'),
('hsr', 'chaos', '루카', '서브 딜러', 'F', 'stay'),
('hsr', 'chaos', '어공', '서포터', 'F', 'stay'),
('hsr', 'chaos', '제레', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '게파드', '유지력', 'F', 'stay'),
('hsr', 'chaos', '웰트', '서포터', 'F', 'stay'),
('hsr', 'chaos', '클라라', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '연경', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '백로', '유지력', 'F', 'stay'),
('hsr', 'chaos', 'Mar. 7th', '유지력', 'F', 'stay'),
('hsr', 'chaos', '단항', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '아스타', '서포터', 'F', 'stay'),
('hsr', 'chaos', '아를란', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '헤르타', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '나타샤', '유지력', 'F', 'stay'),
('hsr', 'chaos', '삼포', '서브 딜러', 'F', 'stay'),
('hsr', 'chaos', '후크', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '서벌', '서브 딜러', 'F', 'stay'),
('hsr', 'chaos', '청작', '메인 딜러', 'F', 'stay'),
('hsr', 'chaos', '소상', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '스파키', '메인 딜러', 'OP', 'stay'),
('hsr', 'fiction', '효광', '서포터', 'OP', 'stay'),
('hsr', 'fiction', '카스토리스', '메인 딜러', 'SS', 'stay'),
('hsr', 'fiction', '히실렌스', '메인 딜러', 'SS', 'stay'),
('hsr', 'fiction', '에버나이트', '서브 딜러', 'SS', 'stay'),
('hsr', 'fiction', '키레네', '서포터', 'SS', 'stay'),
('hsr', 'fiction', '히아킨', '유지력', 'SS', 'stay'),
('hsr', 'fiction', '카프카', '메인 딜러', 'SS', 'stay'),
('hsr', 'fiction', '아낙사', '메인 딜러', 'S+', 'stay'),
('hsr', 'fiction', '트리비', '서포터', 'S+', 'stay'),
('hsr', 'fiction', '단항•등황', '유지력', 'S+', 'stay'),
('hsr', 'fiction', '스파클', '서포터', 'S+', 'stay'),
('hsr', 'fiction', '블랙 스완', '서포터', 'S+', 'stay'),
('hsr', 'fiction', '곽향', '유지력', 'S+', 'stay'),
('hsr', 'fiction', '달리아', '서포터', 'S', 'stay'),
('hsr', 'fiction', '애쉬베일', '서브 딜러', 'S', 'stay'),
('hsr', 'fiction', '더 헤르타', '메인 딜러', 'S', 'stay'),
('hsr', 'fiction', '라파', '메인 딜러', 'S', 'stay'),
('hsr', 'fiction', '영사', '유지력', 'S', 'stay'),
('hsr', 'fiction', '제이드', '메인 딜러', 'S', 'stay'),
('hsr', 'fiction', '헤르타', '메인 딜러', 'S', 'stay'),
('hsr', 'fiction', '마이데이', '메인 딜러', 'A', 'stay'),
('hsr', 'fiction', '파이논', '메인 딜러', 'A', 'stay'),
('hsr', 'fiction', '사이퍼', '서브 딜러', 'A', 'stay'),
('hsr', 'fiction', '케리드라', '서포터', 'A', 'stay'),
('hsr', 'fiction', '반디', '메인 딜러', 'A', 'stay'),
('hsr', 'fiction', '갤러거', '유지력', 'A', 'stay'),
('hsr', 'fiction', '완•매', '서포터', 'A', 'stay'),
('hsr', 'fiction', '아젠티', '메인 딜러', 'A', 'stay'),
('hsr', 'fiction', '망귀인', '서포터', 'B', 'stay'),
('hsr', 'fiction', '아글라이아', '메인 딜러', 'B', 'stay'),
('hsr', 'fiction', '선데이', '서포터', 'B', 'stay'),
('hsr', 'fiction', '로빈', '서포터', 'B', 'stay'),
('hsr', 'fiction', '아케론', '메인 딜러', 'B', 'stay'),
('hsr', 'fiction', '어벤츄린', '유지력', 'B', 'stay'),
('hsr', 'fiction', '부현', '유지력', 'B', 'stay'),
('hsr', 'fiction', '초구', '서포터', 'C', 'stay'),
('hsr', 'fiction', '블레이드', '메인 딜러', 'C', 'stay'),
('hsr', 'fiction', '은랑', '서포터', 'C', 'stay'),
('hsr', 'fiction', '나찰', '유지력', 'C', 'stay'),
('hsr', 'fiction', '히메코', '메인 딜러', 'C', 'stay'),
('hsr', 'fiction', '서벌', '서브 딜러', 'C', 'stay'),
('hsr', 'fiction', '세이버', '메인 딜러', 'D', 'stay'),
('hsr', 'fiction', '운리', '메인 딜러', 'D', 'stay'),
('hsr', 'fiction', '경류', '메인 딜러', 'D', 'stay'),
('hsr', 'fiction', '경원', '메인 딜러', 'D', 'stay'),
('hsr', 'fiction', '브로냐', '서포터', 'D', 'stay'),
('hsr', 'fiction', '정운', '서포터', 'D', 'stay'),
('hsr', 'fiction', '페라', '서포터', 'D', 'stay'),
('hsr', 'fiction', '아처', '메인 딜러', 'E', 'stay'),
('hsr', 'fiction', '계네빈', '서브 딜러', 'E', 'stay'),
('hsr', 'fiction', '클라라', '메인 딜러', 'E', 'stay'),
('hsr', 'fiction', '백로', '유지력', 'E', 'stay'),
('hsr', 'fiction', '게파드', '유지력', 'E', 'stay'),
('hsr', 'fiction', '비소', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '맥택', '서브 딜러', 'F', 'stay'),
('hsr', 'fiction', 'Mar. 7th (수렵)', '서브 딜러', 'F', 'stay'),
('hsr', 'fiction', '부트힐', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '미샤', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', 'Dr. 레이시오', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '설의', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '한아', '서포터', 'F', 'stay'),
('hsr', 'fiction', '토파즈 & 복순이', '서브 딜러', 'F', 'stay'),
('hsr', 'fiction', '링스', '유지력', 'F', 'stay'),
('hsr', 'fiction', '단항•음월', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '루카', '서브 딜러', 'F', 'stay'),
('hsr', 'fiction', '어공', '서포터', 'F', 'stay'),
('hsr', 'fiction', '아를란', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '단항', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '후크', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '청작', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '제레', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '소상', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '연경', '메인 딜러', 'F', 'stay'),
('hsr', 'fiction', '삼포', '서브 딜러', 'F', 'stay'),
('hsr', 'fiction', '웰트', '서포터', 'F', 'stay'),
('hsr', 'fiction', '아스타', '서포터', 'F', 'stay'),
('hsr', 'fiction', 'Mar. 7th', '유지력', 'F', 'stay'),
('hsr', 'fiction', '나타샤', '유지력', 'F', 'stay'),
('hsr', 'shadow', '곽향', '유지력', 'OP', 'stay'),
('hsr', 'shadow', '히아킨', '유지력', 'OP', 'stay'),
('hsr', 'shadow', '단항•등황', '유지력', 'OP', 'stay'),
('hsr', 'shadow', '트리비', '서포터', 'OP', 'stay'),
('hsr', 'shadow', '케리드라', '서포터', 'OP', 'stay'),
('hsr', 'shadow', '키레네', '서포터', 'OP', 'stay'),
('hsr', 'shadow', '반디', '메인 딜러', 'OP', 'stay'),
('hsr', 'shadow', '카스토리스', '메인 딜러', 'OP', 'stay'),
('hsr', 'shadow', '아낙사', '메인 딜러', 'OP', 'stay'),
('hsr', 'shadow', '파이논', '메인 딜러', 'OP', 'stay'),
('hsr', 'shadow', '아처', '메인 딜러', 'OP', 'stay'),
('hsr', 'shadow', '에버나이트', '서브 딜러', 'OP', 'stay'),
('hsr', 'shadow', '영사', '유지력', 'SS', 'stay'),
('hsr', 'shadow', '블랙 스완', '서포터', 'SS', 'stay'),
('hsr', 'shadow', '스파클', '서포터', 'SS', 'stay'),
('hsr', 'shadow', '선데이', '서포터', 'SS', 'stay'),
('hsr', 'shadow', '망귀인', '서포터', 'SS', 'stay'),
('hsr', 'shadow', '달리아', '서포터', 'SS', 'stay'),
('hsr', 'shadow', '카프카', '메인 딜러', 'SS', 'stay'),
('hsr', 'shadow', '부트힐', '메인 딜러', 'SS', 'stay'),
('hsr', 'shadow', '아글라이아', '메인 딜러', 'SS', 'stay'),
('hsr', 'shadow', '애쉬베일', '서브 딜러', 'SS', 'stay'),
('hsr', 'shadow', '히실렌스', '메인 딜러', 'SS', 'stay'),
('hsr', 'shadow', '로빈', '서포터', 'S+', 'stay'),
('hsr', 'shadow', '정운', '서포터', 'S+', 'stay'),
('hsr', 'shadow', '사이퍼', '서브 딜러', 'S+', 'stay'),
('hsr', 'shadow', '아케론', '메인 딜러', 'S+', 'stay'),
('hsr', 'shadow', '비소', '메인 딜러', 'S+', 'stay'),
('hsr', 'shadow', '라파', '메인 딜러', 'S+', 'stay'),
('hsr', 'shadow', '더 헤르타', '메인 딜러', 'S+', 'stay'),
('hsr', 'shadow', '마이데이', '메인 딜러', 'S+', 'stay'),
('hsr', 'shadow', '세이버', '메인 딜러', 'S+', 'stay'),
('hsr', 'shadow', '완•매', '서포터', 'S', 'stay'),
('hsr', 'shadow', '갤러거', '유지력', 'A', 'stay'),
('hsr', 'shadow', '어벤츄린', '유지력', 'B', 'stay'),
('hsr', 'shadow', '제이드', '메인 딜러', 'C', 'stay')
ON CONFLICT (game_id, category_id, character_name) DO UPDATE SET tier = EXCLUDED.tier, change = EXCLUDED.change, role = EXCLUDED.role;